[theme]
theme = "dracula"
#theme = "space-villain"
[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:15) |"
short = " $title.str(max_w:10) |"
[block.theme_overrides]
idle_bg = "#FFFFFF"
idle_fg = "#000000"

[[block]]
block = "sound"
driver = "auto"
format = " $icon { $volume|} "
[block.theme_overrides]
idle_bg = "#b39ddb"
idle_fg = "#000000"

[[block]]
block = "music"
format = " $icon $volume_icon $combo $play $next| "
seek_step_secs = 10
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]]
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"


#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#
#[[block]]
#block = "disk_space"
#path = "/home"
#alias = "/home"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#
#[[block]]
#block = "disk_space"
#path = "/media/Data"
#alias = "Data"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

#[[block]]
#block = "xrandr"
#format = " $icon $brightness $resolution "
#[block.theme_overrides]
#idle_bg = "#af00ff"
#idle_fg = "#FFFFFF"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90
[block.theme_overrides]
idle_bg = "#7e57c2"
idle_fg = "#FFFFFF"

[[block]]
block = "load"
#format = " $icon 1min avg: $1m.eng(w:4) "
format = " $icon $1m.eng(w:4) "
interval = 1
[block.theme_overrides]
idle_bg = "#673ab7"
idle_fg = "#FFFFFF"

[[block]]
block = "net"
#format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "
#format = " $icon {$signal_strength $ssid $frequency|Wired connection}"
format = " $icon {$signal_strength $ssid|$ip }"
[block.theme_overrides]
idle_bg = "#512da8"
idle_fg = "#FFFFFF"
 
#[[block]]
#block = "external_ip"
#format = " $ip $country_code "

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z') "
#short = " $icon $timestamp.datetime(f:%R) "
[block.theme_overrides]
idle_bg = "#311b92"
idle_fg = "#FFFFFF"

#[[block]]
#block = "nvidia_gpu"
#interval = 1
#format = " $icon RTX 3060 $utilization $temperature $clocks "


[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-pci-*"

#[[block]]
#block = "battery"
#format = " $icon $percentage {$time |} $power "
#device = "BAT"
#driver = "sysfs"


[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
[block.theme_overrides]
idle_bg = "#ffe800"
idle_fg = "#000000"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15
[block.theme_overrides]
idle_bg = "#00a0ff"
idle_fg = "#FFFFFF"

#[[block]]
#block = "watson"
#show_time = true
#state_path = "~/.config/watson/state"
